# Generated by Django 3.1.2 on 2021-01-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
