# Generated by Django 3.1.2 on 2020-12-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcube', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(default='addidas', max_length=30),
            preserve_default=False,
        ),
    ]
