# Generated by Django 3.1.2 on 2020-12-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcube', '0006_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user_id',
            new_name='user',
        ),
    ]
