# Generated by Django 3.1.2 on 2021-01-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcube', '0003_auto_20210124_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
