# Generated by Django 3.1.2 on 2021-01-24 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcube', '0004_question_is_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ques',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pcube.question'),
        ),
    ]
