# Generated by Django 3.1.2 on 2021-01-25 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pcube', '0005_answer_ques'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ques',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pcube.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='queslikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='notify',
            field=models.ManyToManyField(blank=True, related_name='notify', to=settings.AUTH_USER_MODEL),
        ),
    ]
