# Generated by Django 3.1.2 on 2021-01-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcube', '0006_auto_20210125_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques',
            field=models.CharField(max_length=150),
        ),
    ]
