# Generated by Django 3.1.2 on 2021-01-25 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pcube', '0007_auto_20210125_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
