# Generated by Django 3.1.2 on 2021-01-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcube', '0008_question_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='showed',
            field=models.BooleanField(default=False),
        ),
    ]
